name: "local-dcs"
net: 0x02
genesis_param: 
  fee_per_tx_kb: 0
  consensus_algorithm: "bls"
  block_timestamp: "2019-11-29T00:00:00.000Z"
  tx_stake: "d0e731f55fa6c49f602807a6686a7ac769de4e04882bb5eaf8f4fe209f46535d"
committee_size:
  max_shard_committee_size: 16
  min_shard_committee_size: 8
  min_beacon_committee_size: 4
  max_beacon_committee_size: 7
  init_shard_committee_size: 8
  init_beacon_committee_size: 4
  shard_committee_size_key_list_v2: 8
  beacon_committee_size_key_list_v2: 4
  number_of_fixed_shard_block_validators: 8
  increase_max_shard_committee_size:
    - 1000000000000: 48
block_time:
  min_beacon_block_interval: 10s 
  max_beacon_block_creation: 8s
  min_shard_block_interval: 10s
  max_shard_block_creation: 6s
staking_amount_shard: 1750000000000
staking_amount_beacon: 87500000000000
active_shards: 1
basic_reward: 400000000
epoch_param:
  number_of_block_in_epoch: 10
  number_of_block_in_epoch_v2: 1000000000000
  epoch_v2_break_point: 1000000000000
  random_time: 5
  random_time_v2: 1000000000000
eth_contract_address: "0xE0D5e7217c6C4bc475404b26d763fAD3F14D2b86"
plg_contract_address: ""
dao_address: "12S5Lrs1XeQLbqN4ySyKtjAjd2d7sBP2tjFijzmp6avrrkQCNFMpkXm3FPzj2Wcu2ZNqJEmh9JriVuRErVwhuQnLmWSaggobEWsBEci" # community fund
centralized_website_payment_address: "12S5Lrs1XeQLbqN4ySyKtjAjd2d7sBP2tjFijzmp6avrrkQCNFMpkXm3FPzj2Wcu2ZNqJEmh9JriVuRErVwhuQnLmWSaggobEWsBEci"
swap_committee_param:
  offset: 1
  swap_offset: 1
  assign_offset: 2
consensus_param:
  consensus_v2_epoch: 1
  staking_flow_v2_height: 1
  enable_slashing_height: 1
  enable_slashing_height_v2: 1
  assign_rule_v3_height: 1
  staking_flow_v3_height: 1
  force_not_use_burned_coins: 1
  lemma2_height: 1
  byzantine_detector_height: 1
  block_producing_v3_height: 1000000000
  timeslot: 10
  epoch_break_point_swap_new_key: 
    - 1000000000
beacon_height_break_point_burn_addr: 1
eth_remove_bridge_sig_epoch: 21920
replace_staking_tx_height: 1
bc_height_break_point_new_zkp: 1148608
enable_feature_flags:
  - 0: 1
  - 1: 0
portal_v3_height: 1000000000000
tx_pool_version: 0
geth_param:
  host: 
    - "https://kovan.infura.io/v3/1138a1e99b154b10bae5c382ad894361"
bsc_param:
  host: 
    - "https://data-seed-prebsc-2-s2.binance.org:8545"
plg_param:
  host: 
    - "https://polygon-mumbai.g.alchemy.com/v2/V8SP0S8Q-sT35ca4VKH3Iwyvh8K8wTRn"
pdex_param:
  pdex_v3_break_point_height: 11
  protocol_fund_address: "12svfkP6w5UDJDSCwqH978PvqiqBxKmUnA9em9yAYWYJVRv7wuXY1qhhYpPAm4BDz2mLbFrRmdK3yRhnTqJCZXKHUmoi7NV83HCH2YFpctHNaDdkSiQshsjw2UFUuwdEvcidgaKmF3VJpY5f8RdN"
  admin_address: "12svfkP6w5UDJDSCwqH978PvqiqBxKmUnA9em9yAYWYJVRv7wuXY1qhhYpPAm4BDz2mLbFrRmdK3yRhnTqJCZXKHUmoi7NV83HCH2YFpctHNaDdkSiQshsjw2UFUuwdEvcidgaKmF3VJpY5f8RdN"
  params:
    default_fee_rate_bps: 30
    prv_discount_percent: 25
    trading_protocol_fee_percent: 0
    trading_staking_pool_reward_percent: 10
    staking_pool_share:
      - "0000000000000000000000000000000000000000000000000000000000000004": 10
      - "0000000000000000000000000000000000000000000000000000000000000006": 20
    mint_nft_require_amount: 1000000000
    max_orders_per_nft: 10
    auto_withdraw_order_limit_amount: 10
    min_prv_reserve_trading_rate: 1000000000000
is_enable_bpv3_stats: true