// Code generated by protoc-gen-go. DO NOT EDIT.
// source: highway.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MessageTopicPair_Action int32

const (
	MessageTopicPair_PUBSUB MessageTopicPair_Action = 0
	MessageTopicPair_PUB    MessageTopicPair_Action = 1
	MessageTopicPair_SUB    MessageTopicPair_Action = 2
)

var MessageTopicPair_Action_name = map[int32]string{
	0: "PUBSUB",
	1: "PUB",
	2: "SUB",
}

var MessageTopicPair_Action_value = map[string]int32{
	"PUBSUB": 0,
	"PUB":    1,
	"SUB":    2,
}

func (x MessageTopicPair_Action) String() string {
	return proto.EnumName(MessageTopicPair_Action_name, int32(x))
}

func (MessageTopicPair_Action) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a48762df9e8cc53a, []int{3, 0}
}

type RegisterRequest struct {
	CommitteePublicKey   string   `protobuf:"bytes,1,opt,name=CommitteePublicKey,proto3" json:"CommitteePublicKey,omitempty"`
	WantedMessages       []string `protobuf:"bytes,2,rep,name=WantedMessages,proto3" json:"WantedMessages,omitempty"`
	CommitteeID          []byte   `protobuf:"bytes,3,opt,name=CommitteeID,proto3" json:"CommitteeID,omitempty"`
	PeerID               string   `protobuf:"bytes,4,opt,name=PeerID,proto3" json:"PeerID,omitempty"`
	Role                 string   `protobuf:"bytes,5,opt,name=Role,proto3" json:"Role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a48762df9e8cc53a, []int{0}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetCommitteePublicKey() string {
	if m != nil {
		return m.CommitteePublicKey
	}
	return ""
}

func (m *RegisterRequest) GetWantedMessages() []string {
	if m != nil {
		return m.WantedMessages
	}
	return nil
}

func (m *RegisterRequest) GetCommitteeID() []byte {
	if m != nil {
		return m.CommitteeID
	}
	return nil
}

func (m *RegisterRequest) GetPeerID() string {
	if m != nil {
		return m.PeerID
	}
	return ""
}

func (m *RegisterRequest) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

type UserRole struct {
	Layer                string   `protobuf:"bytes,1,opt,name=Layer,proto3" json:"Layer,omitempty"`
	Role                 string   `protobuf:"bytes,2,opt,name=Role,proto3" json:"Role,omitempty"`
	Shard                int32    `protobuf:"varint,3,opt,name=Shard,proto3" json:"Shard,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRole) Reset()         { *m = UserRole{} }
func (m *UserRole) String() string { return proto.CompactTextString(m) }
func (*UserRole) ProtoMessage()    {}
func (*UserRole) Descriptor() ([]byte, []int) {
	return fileDescriptor_a48762df9e8cc53a, []int{1}
}

func (m *UserRole) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRole.Unmarshal(m, b)
}
func (m *UserRole) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRole.Marshal(b, m, deterministic)
}
func (m *UserRole) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRole.Merge(m, src)
}
func (m *UserRole) XXX_Size() int {
	return xxx_messageInfo_UserRole.Size(m)
}
func (m *UserRole) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRole.DiscardUnknown(m)
}

var xxx_messageInfo_UserRole proto.InternalMessageInfo

func (m *UserRole) GetLayer() string {
	if m != nil {
		return m.Layer
	}
	return ""
}

func (m *UserRole) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *UserRole) GetShard() int32 {
	if m != nil {
		return m.Shard
	}
	return 0
}

type RegisterResponse struct {
	Pair                 []*MessageTopicPair `protobuf:"bytes,1,rep,name=Pair,proto3" json:"Pair,omitempty"`
	Role                 *UserRole           `protobuf:"bytes,2,opt,name=Role,proto3" json:"Role,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a48762df9e8cc53a, []int{2}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetPair() []*MessageTopicPair {
	if m != nil {
		return m.Pair
	}
	return nil
}

func (m *RegisterResponse) GetRole() *UserRole {
	if m != nil {
		return m.Role
	}
	return nil
}

type MessageTopicPair struct {
	Message              string                    `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	Topic                []string                  `protobuf:"bytes,2,rep,name=Topic,proto3" json:"Topic,omitempty"`
	Act                  []MessageTopicPair_Action `protobuf:"varint,3,rep,packed,name=Act,proto3,enum=MessageTopicPair_Action" json:"Act,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *MessageTopicPair) Reset()         { *m = MessageTopicPair{} }
func (m *MessageTopicPair) String() string { return proto.CompactTextString(m) }
func (*MessageTopicPair) ProtoMessage()    {}
func (*MessageTopicPair) Descriptor() ([]byte, []int) {
	return fileDescriptor_a48762df9e8cc53a, []int{3}
}

func (m *MessageTopicPair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageTopicPair.Unmarshal(m, b)
}
func (m *MessageTopicPair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageTopicPair.Marshal(b, m, deterministic)
}
func (m *MessageTopicPair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageTopicPair.Merge(m, src)
}
func (m *MessageTopicPair) XXX_Size() int {
	return xxx_messageInfo_MessageTopicPair.Size(m)
}
func (m *MessageTopicPair) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageTopicPair.DiscardUnknown(m)
}

var xxx_messageInfo_MessageTopicPair proto.InternalMessageInfo

func (m *MessageTopicPair) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *MessageTopicPair) GetTopic() []string {
	if m != nil {
		return m.Topic
	}
	return nil
}

func (m *MessageTopicPair) GetAct() []MessageTopicPair_Action {
	if m != nil {
		return m.Act
	}
	return nil
}

type GetBlockShardByHeightRequest struct {
	Shard                int32    `protobuf:"varint,1,opt,name=Shard,proto3" json:"Shard,omitempty"`
	Specific             bool     `protobuf:"varint,2,opt,name=Specific,proto3" json:"Specific,omitempty"`
	FromHeight           uint64   `protobuf:"varint,3,opt,name=FromHeight,proto3" json:"FromHeight,omitempty"`
	ToHeight             uint64   `protobuf:"varint,4,opt,name=ToHeight,proto3" json:"ToHeight,omitempty"`
	Heights              []uint64 `protobuf:"varint,5,rep,packed,name=Heights,proto3" json:"Heights,omitempty"`
	FromPool             bool     `protobuf:"varint,6,opt,name=FromPool,proto3" json:"FromPool,omitempty"`
	CallDepth            int32    `protobuf:"varint,7,opt,name=CallDepth,proto3" json:"CallDepth,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockShardByHeightRequest) Reset()         { *m = GetBlockShardByHeightRequest{} }
func (m *GetBlockShardByHeightRequest) String() string { return proto.CompactTextString(m) }
func (*GetBlockShardByHeightRequest) ProtoMessage()    {}
func (*GetBlockShardByHeightRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a48762df9e8cc53a, []int{4}
}

func (m *GetBlockShardByHeightRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockShardByHeightRequest.Unmarshal(m, b)
}
func (m *GetBlockShardByHeightRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockShardByHeightRequest.Marshal(b, m, deterministic)
}
func (m *GetBlockShardByHeightRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockShardByHeightRequest.Merge(m, src)
}
func (m *GetBlockShardByHeightRequest) XXX_Size() int {
	return xxx_messageInfo_GetBlockShardByHeightRequest.Size(m)
}
func (m *GetBlockShardByHeightRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockShardByHeightRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockShardByHeightRequest proto.InternalMessageInfo

func (m *GetBlockShardByHeightRequest) GetShard() int32 {
	if m != nil {
		return m.Shard
	}
	return 0
}

func (m *GetBlockShardByHeightRequest) GetSpecific() bool {
	if m != nil {
		return m.Specific
	}
	return false
}

func (m *GetBlockShardByHeightRequest) GetFromHeight() uint64 {
	if m != nil {
		return m.FromHeight
	}
	return 0
}

func (m *GetBlockShardByHeightRequest) GetToHeight() uint64 {
	if m != nil {
		return m.ToHeight
	}
	return 0
}

func (m *GetBlockShardByHeightRequest) GetHeights() []uint64 {
	if m != nil {
		return m.Heights
	}
	return nil
}

func (m *GetBlockShardByHeightRequest) GetFromPool() bool {
	if m != nil {
		return m.FromPool
	}
	return false
}

func (m *GetBlockShardByHeightRequest) GetCallDepth() int32 {
	if m != nil {
		return m.CallDepth
	}
	return 0
}

type GetBlockShardByHeightResponse struct {
	Data                 [][]byte `protobuf:"bytes,1,rep,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockShardByHeightResponse) Reset()         { *m = GetBlockShardByHeightResponse{} }
func (m *GetBlockShardByHeightResponse) String() string { return proto.CompactTextString(m) }
func (*GetBlockShardByHeightResponse) ProtoMessage()    {}
func (*GetBlockShardByHeightResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a48762df9e8cc53a, []int{5}
}

func (m *GetBlockShardByHeightResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockShardByHeightResponse.Unmarshal(m, b)
}
func (m *GetBlockShardByHeightResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockShardByHeightResponse.Marshal(b, m, deterministic)
}
func (m *GetBlockShardByHeightResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockShardByHeightResponse.Merge(m, src)
}
func (m *GetBlockShardByHeightResponse) XXX_Size() int {
	return xxx_messageInfo_GetBlockShardByHeightResponse.Size(m)
}
func (m *GetBlockShardByHeightResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockShardByHeightResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockShardByHeightResponse proto.InternalMessageInfo

func (m *GetBlockShardByHeightResponse) GetData() [][]byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetBlockShardByHashRequest struct {
	Shard                int32    `protobuf:"varint,1,opt,name=Shard,proto3" json:"Shard,omitempty"`
	Hashes               [][]byte `protobuf:"bytes,2,rep,name=Hashes,proto3" json:"Hashes,omitempty"`
	CallDepth            int32    `protobuf:"varint,3,opt,name=CallDepth,proto3" json:"CallDepth,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockShardByHashRequest) Reset()         { *m = GetBlockShardByHashRequest{} }
func (m *GetBlockShardByHashRequest) String() string { return proto.CompactTextString(m) }
func (*GetBlockShardByHashRequest) ProtoMessage()    {}
func (*GetBlockShardByHashRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a48762df9e8cc53a, []int{6}
}

func (m *GetBlockShardByHashRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockShardByHashRequest.Unmarshal(m, b)
}
func (m *GetBlockShardByHashRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockShardByHashRequest.Marshal(b, m, deterministic)
}
func (m *GetBlockShardByHashRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockShardByHashRequest.Merge(m, src)
}
func (m *GetBlockShardByHashRequest) XXX_Size() int {
	return xxx_messageInfo_GetBlockShardByHashRequest.Size(m)
}
func (m *GetBlockShardByHashRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockShardByHashRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockShardByHashRequest proto.InternalMessageInfo

func (m *GetBlockShardByHashRequest) GetShard() int32 {
	if m != nil {
		return m.Shard
	}
	return 0
}

func (m *GetBlockShardByHashRequest) GetHashes() [][]byte {
	if m != nil {
		return m.Hashes
	}
	return nil
}

func (m *GetBlockShardByHashRequest) GetCallDepth() int32 {
	if m != nil {
		return m.CallDepth
	}
	return 0
}

type GetBlockShardByHashResponse struct {
	Data                 [][]byte `protobuf:"bytes,1,rep,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockShardByHashResponse) Reset()         { *m = GetBlockShardByHashResponse{} }
func (m *GetBlockShardByHashResponse) String() string { return proto.CompactTextString(m) }
func (*GetBlockShardByHashResponse) ProtoMessage()    {}
func (*GetBlockShardByHashResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a48762df9e8cc53a, []int{7}
}

func (m *GetBlockShardByHashResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockShardByHashResponse.Unmarshal(m, b)
}
func (m *GetBlockShardByHashResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockShardByHashResponse.Marshal(b, m, deterministic)
}
func (m *GetBlockShardByHashResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockShardByHashResponse.Merge(m, src)
}
func (m *GetBlockShardByHashResponse) XXX_Size() int {
	return xxx_messageInfo_GetBlockShardByHashResponse.Size(m)
}
func (m *GetBlockShardByHashResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockShardByHashResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockShardByHashResponse proto.InternalMessageInfo

func (m *GetBlockShardByHashResponse) GetData() [][]byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetBlockBeaconByHeightRequest struct {
	Specific             bool     `protobuf:"varint,1,opt,name=Specific,proto3" json:"Specific,omitempty"`
	FromHeight           uint64   `protobuf:"varint,2,opt,name=FromHeight,proto3" json:"FromHeight,omitempty"`
	ToHeight             uint64   `protobuf:"varint,3,opt,name=ToHeight,proto3" json:"ToHeight,omitempty"`
	Heights              []uint64 `protobuf:"varint,4,rep,packed,name=Heights,proto3" json:"Heights,omitempty"`
	FromPool             bool     `protobuf:"varint,5,opt,name=FromPool,proto3" json:"FromPool,omitempty"`
	CallDepth            int32    `protobuf:"varint,6,opt,name=CallDepth,proto3" json:"CallDepth,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockBeaconByHeightRequest) Reset()         { *m = GetBlockBeaconByHeightRequest{} }
func (m *GetBlockBeaconByHeightRequest) String() string { return proto.CompactTextString(m) }
func (*GetBlockBeaconByHeightRequest) ProtoMessage()    {}
func (*GetBlockBeaconByHeightRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a48762df9e8cc53a, []int{8}
}

func (m *GetBlockBeaconByHeightRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockBeaconByHeightRequest.Unmarshal(m, b)
}
func (m *GetBlockBeaconByHeightRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockBeaconByHeightRequest.Marshal(b, m, deterministic)
}
func (m *GetBlockBeaconByHeightRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockBeaconByHeightRequest.Merge(m, src)
}
func (m *GetBlockBeaconByHeightRequest) XXX_Size() int {
	return xxx_messageInfo_GetBlockBeaconByHeightRequest.Size(m)
}
func (m *GetBlockBeaconByHeightRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockBeaconByHeightRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockBeaconByHeightRequest proto.InternalMessageInfo

func (m *GetBlockBeaconByHeightRequest) GetSpecific() bool {
	if m != nil {
		return m.Specific
	}
	return false
}

func (m *GetBlockBeaconByHeightRequest) GetFromHeight() uint64 {
	if m != nil {
		return m.FromHeight
	}
	return 0
}

func (m *GetBlockBeaconByHeightRequest) GetToHeight() uint64 {
	if m != nil {
		return m.ToHeight
	}
	return 0
}

func (m *GetBlockBeaconByHeightRequest) GetHeights() []uint64 {
	if m != nil {
		return m.Heights
	}
	return nil
}

func (m *GetBlockBeaconByHeightRequest) GetFromPool() bool {
	if m != nil {
		return m.FromPool
	}
	return false
}

func (m *GetBlockBeaconByHeightRequest) GetCallDepth() int32 {
	if m != nil {
		return m.CallDepth
	}
	return 0
}

type GetBlockBeaconByHeightResponse struct {
	Data                 [][]byte `protobuf:"bytes,1,rep,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockBeaconByHeightResponse) Reset()         { *m = GetBlockBeaconByHeightResponse{} }
func (m *GetBlockBeaconByHeightResponse) String() string { return proto.CompactTextString(m) }
func (*GetBlockBeaconByHeightResponse) ProtoMessage()    {}
func (*GetBlockBeaconByHeightResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a48762df9e8cc53a, []int{9}
}

func (m *GetBlockBeaconByHeightResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockBeaconByHeightResponse.Unmarshal(m, b)
}
func (m *GetBlockBeaconByHeightResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockBeaconByHeightResponse.Marshal(b, m, deterministic)
}
func (m *GetBlockBeaconByHeightResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockBeaconByHeightResponse.Merge(m, src)
}
func (m *GetBlockBeaconByHeightResponse) XXX_Size() int {
	return xxx_messageInfo_GetBlockBeaconByHeightResponse.Size(m)
}
func (m *GetBlockBeaconByHeightResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockBeaconByHeightResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockBeaconByHeightResponse proto.InternalMessageInfo

func (m *GetBlockBeaconByHeightResponse) GetData() [][]byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetBlockBeaconByHashRequest struct {
	Hashes               [][]byte `protobuf:"bytes,1,rep,name=Hashes,proto3" json:"Hashes,omitempty"`
	CallDepth            int32    `protobuf:"varint,2,opt,name=CallDepth,proto3" json:"CallDepth,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockBeaconByHashRequest) Reset()         { *m = GetBlockBeaconByHashRequest{} }
func (m *GetBlockBeaconByHashRequest) String() string { return proto.CompactTextString(m) }
func (*GetBlockBeaconByHashRequest) ProtoMessage()    {}
func (*GetBlockBeaconByHashRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a48762df9e8cc53a, []int{10}
}

func (m *GetBlockBeaconByHashRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockBeaconByHashRequest.Unmarshal(m, b)
}
func (m *GetBlockBeaconByHashRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockBeaconByHashRequest.Marshal(b, m, deterministic)
}
func (m *GetBlockBeaconByHashRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockBeaconByHashRequest.Merge(m, src)
}
func (m *GetBlockBeaconByHashRequest) XXX_Size() int {
	return xxx_messageInfo_GetBlockBeaconByHashRequest.Size(m)
}
func (m *GetBlockBeaconByHashRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockBeaconByHashRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockBeaconByHashRequest proto.InternalMessageInfo

func (m *GetBlockBeaconByHashRequest) GetHashes() [][]byte {
	if m != nil {
		return m.Hashes
	}
	return nil
}

func (m *GetBlockBeaconByHashRequest) GetCallDepth() int32 {
	if m != nil {
		return m.CallDepth
	}
	return 0
}

type GetBlockBeaconByHashResponse struct {
	Data                 [][]byte `protobuf:"bytes,1,rep,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockBeaconByHashResponse) Reset()         { *m = GetBlockBeaconByHashResponse{} }
func (m *GetBlockBeaconByHashResponse) String() string { return proto.CompactTextString(m) }
func (*GetBlockBeaconByHashResponse) ProtoMessage()    {}
func (*GetBlockBeaconByHashResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a48762df9e8cc53a, []int{11}
}

func (m *GetBlockBeaconByHashResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockBeaconByHashResponse.Unmarshal(m, b)
}
func (m *GetBlockBeaconByHashResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockBeaconByHashResponse.Marshal(b, m, deterministic)
}
func (m *GetBlockBeaconByHashResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockBeaconByHashResponse.Merge(m, src)
}
func (m *GetBlockBeaconByHashResponse) XXX_Size() int {
	return xxx_messageInfo_GetBlockBeaconByHashResponse.Size(m)
}
func (m *GetBlockBeaconByHashResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockBeaconByHashResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockBeaconByHashResponse proto.InternalMessageInfo

func (m *GetBlockBeaconByHashResponse) GetData() [][]byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetBlockCrossShardByHeightRequest struct {
	FromShard            int32    `protobuf:"varint,1,opt,name=FromShard,proto3" json:"FromShard,omitempty"`
	ToShard              int32    `protobuf:"varint,2,opt,name=ToShard,proto3" json:"ToShard,omitempty"`
	Specific             bool     `protobuf:"varint,3,opt,name=Specific,proto3" json:"Specific,omitempty"`
	FromHeight           uint64   `protobuf:"varint,4,opt,name=FromHeight,proto3" json:"FromHeight,omitempty"`
	ToHeight             uint64   `protobuf:"varint,5,opt,name=ToHeight,proto3" json:"ToHeight,omitempty"`
	Heights              []uint64 `protobuf:"varint,6,rep,packed,name=Heights,proto3" json:"Heights,omitempty"`
	FromPool             bool     `protobuf:"varint,7,opt,name=FromPool,proto3" json:"FromPool,omitempty"`
	CallDepth            int32    `protobuf:"varint,8,opt,name=CallDepth,proto3" json:"CallDepth,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockCrossShardByHeightRequest) Reset()         { *m = GetBlockCrossShardByHeightRequest{} }
func (m *GetBlockCrossShardByHeightRequest) String() string { return proto.CompactTextString(m) }
func (*GetBlockCrossShardByHeightRequest) ProtoMessage()    {}
func (*GetBlockCrossShardByHeightRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a48762df9e8cc53a, []int{12}
}

func (m *GetBlockCrossShardByHeightRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockCrossShardByHeightRequest.Unmarshal(m, b)
}
func (m *GetBlockCrossShardByHeightRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockCrossShardByHeightRequest.Marshal(b, m, deterministic)
}
func (m *GetBlockCrossShardByHeightRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockCrossShardByHeightRequest.Merge(m, src)
}
func (m *GetBlockCrossShardByHeightRequest) XXX_Size() int {
	return xxx_messageInfo_GetBlockCrossShardByHeightRequest.Size(m)
}
func (m *GetBlockCrossShardByHeightRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockCrossShardByHeightRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockCrossShardByHeightRequest proto.InternalMessageInfo

func (m *GetBlockCrossShardByHeightRequest) GetFromShard() int32 {
	if m != nil {
		return m.FromShard
	}
	return 0
}

func (m *GetBlockCrossShardByHeightRequest) GetToShard() int32 {
	if m != nil {
		return m.ToShard
	}
	return 0
}

func (m *GetBlockCrossShardByHeightRequest) GetSpecific() bool {
	if m != nil {
		return m.Specific
	}
	return false
}

func (m *GetBlockCrossShardByHeightRequest) GetFromHeight() uint64 {
	if m != nil {
		return m.FromHeight
	}
	return 0
}

func (m *GetBlockCrossShardByHeightRequest) GetToHeight() uint64 {
	if m != nil {
		return m.ToHeight
	}
	return 0
}

func (m *GetBlockCrossShardByHeightRequest) GetHeights() []uint64 {
	if m != nil {
		return m.Heights
	}
	return nil
}

func (m *GetBlockCrossShardByHeightRequest) GetFromPool() bool {
	if m != nil {
		return m.FromPool
	}
	return false
}

func (m *GetBlockCrossShardByHeightRequest) GetCallDepth() int32 {
	if m != nil {
		return m.CallDepth
	}
	return 0
}

type GetBlockCrossShardByHeightResponse struct {
	Data                 [][]byte `protobuf:"bytes,1,rep,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockCrossShardByHeightResponse) Reset()         { *m = GetBlockCrossShardByHeightResponse{} }
func (m *GetBlockCrossShardByHeightResponse) String() string { return proto.CompactTextString(m) }
func (*GetBlockCrossShardByHeightResponse) ProtoMessage()    {}
func (*GetBlockCrossShardByHeightResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a48762df9e8cc53a, []int{13}
}

func (m *GetBlockCrossShardByHeightResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockCrossShardByHeightResponse.Unmarshal(m, b)
}
func (m *GetBlockCrossShardByHeightResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockCrossShardByHeightResponse.Marshal(b, m, deterministic)
}
func (m *GetBlockCrossShardByHeightResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockCrossShardByHeightResponse.Merge(m, src)
}
func (m *GetBlockCrossShardByHeightResponse) XXX_Size() int {
	return xxx_messageInfo_GetBlockCrossShardByHeightResponse.Size(m)
}
func (m *GetBlockCrossShardByHeightResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockCrossShardByHeightResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockCrossShardByHeightResponse proto.InternalMessageInfo

func (m *GetBlockCrossShardByHeightResponse) GetData() [][]byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetBlockShardToBeaconByHeightRequest struct {
	FromShard            int32    `protobuf:"varint,1,opt,name=FromShard,proto3" json:"FromShard,omitempty"`
	Specific             bool     `protobuf:"varint,2,opt,name=Specific,proto3" json:"Specific,omitempty"`
	FromHeight           uint64   `protobuf:"varint,3,opt,name=FromHeight,proto3" json:"FromHeight,omitempty"`
	ToHeight             uint64   `protobuf:"varint,4,opt,name=ToHeight,proto3" json:"ToHeight,omitempty"`
	Heights              []uint64 `protobuf:"varint,5,rep,packed,name=Heights,proto3" json:"Heights,omitempty"`
	FromPool             bool     `protobuf:"varint,6,opt,name=FromPool,proto3" json:"FromPool,omitempty"`
	CallDepth            int32    `protobuf:"varint,7,opt,name=CallDepth,proto3" json:"CallDepth,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockShardToBeaconByHeightRequest) Reset()         { *m = GetBlockShardToBeaconByHeightRequest{} }
func (m *GetBlockShardToBeaconByHeightRequest) String() string { return proto.CompactTextString(m) }
func (*GetBlockShardToBeaconByHeightRequest) ProtoMessage()    {}
func (*GetBlockShardToBeaconByHeightRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a48762df9e8cc53a, []int{14}
}

func (m *GetBlockShardToBeaconByHeightRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockShardToBeaconByHeightRequest.Unmarshal(m, b)
}
func (m *GetBlockShardToBeaconByHeightRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockShardToBeaconByHeightRequest.Marshal(b, m, deterministic)
}
func (m *GetBlockShardToBeaconByHeightRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockShardToBeaconByHeightRequest.Merge(m, src)
}
func (m *GetBlockShardToBeaconByHeightRequest) XXX_Size() int {
	return xxx_messageInfo_GetBlockShardToBeaconByHeightRequest.Size(m)
}
func (m *GetBlockShardToBeaconByHeightRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockShardToBeaconByHeightRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockShardToBeaconByHeightRequest proto.InternalMessageInfo

func (m *GetBlockShardToBeaconByHeightRequest) GetFromShard() int32 {
	if m != nil {
		return m.FromShard
	}
	return 0
}

func (m *GetBlockShardToBeaconByHeightRequest) GetSpecific() bool {
	if m != nil {
		return m.Specific
	}
	return false
}

func (m *GetBlockShardToBeaconByHeightRequest) GetFromHeight() uint64 {
	if m != nil {
		return m.FromHeight
	}
	return 0
}

func (m *GetBlockShardToBeaconByHeightRequest) GetToHeight() uint64 {
	if m != nil {
		return m.ToHeight
	}
	return 0
}

func (m *GetBlockShardToBeaconByHeightRequest) GetHeights() []uint64 {
	if m != nil {
		return m.Heights
	}
	return nil
}

func (m *GetBlockShardToBeaconByHeightRequest) GetFromPool() bool {
	if m != nil {
		return m.FromPool
	}
	return false
}

func (m *GetBlockShardToBeaconByHeightRequest) GetCallDepth() int32 {
	if m != nil {
		return m.CallDepth
	}
	return 0
}

type GetBlockShardToBeaconByHeightResponse struct {
	Data                 [][]byte `protobuf:"bytes,1,rep,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockShardToBeaconByHeightResponse) Reset()         { *m = GetBlockShardToBeaconByHeightResponse{} }
func (m *GetBlockShardToBeaconByHeightResponse) String() string { return proto.CompactTextString(m) }
func (*GetBlockShardToBeaconByHeightResponse) ProtoMessage()    {}
func (*GetBlockShardToBeaconByHeightResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a48762df9e8cc53a, []int{15}
}

func (m *GetBlockShardToBeaconByHeightResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockShardToBeaconByHeightResponse.Unmarshal(m, b)
}
func (m *GetBlockShardToBeaconByHeightResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockShardToBeaconByHeightResponse.Marshal(b, m, deterministic)
}
func (m *GetBlockShardToBeaconByHeightResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockShardToBeaconByHeightResponse.Merge(m, src)
}
func (m *GetBlockShardToBeaconByHeightResponse) XXX_Size() int {
	return xxx_messageInfo_GetBlockShardToBeaconByHeightResponse.Size(m)
}
func (m *GetBlockShardToBeaconByHeightResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockShardToBeaconByHeightResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockShardToBeaconByHeightResponse proto.InternalMessageInfo

func (m *GetBlockShardToBeaconByHeightResponse) GetData() [][]byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetBlockCrossShardByHashRequest struct {
	FromShard            int32    `protobuf:"varint,1,opt,name=FromShard,proto3" json:"FromShard,omitempty"`
	ToShard              int32    `protobuf:"varint,2,opt,name=ToShard,proto3" json:"ToShard,omitempty"`
	Hashes               [][]byte `protobuf:"bytes,3,rep,name=Hashes,proto3" json:"Hashes,omitempty"`
	CallDepth            int32    `protobuf:"varint,4,opt,name=CallDepth,proto3" json:"CallDepth,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockCrossShardByHashRequest) Reset()         { *m = GetBlockCrossShardByHashRequest{} }
func (m *GetBlockCrossShardByHashRequest) String() string { return proto.CompactTextString(m) }
func (*GetBlockCrossShardByHashRequest) ProtoMessage()    {}
func (*GetBlockCrossShardByHashRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a48762df9e8cc53a, []int{16}
}

func (m *GetBlockCrossShardByHashRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockCrossShardByHashRequest.Unmarshal(m, b)
}
func (m *GetBlockCrossShardByHashRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockCrossShardByHashRequest.Marshal(b, m, deterministic)
}
func (m *GetBlockCrossShardByHashRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockCrossShardByHashRequest.Merge(m, src)
}
func (m *GetBlockCrossShardByHashRequest) XXX_Size() int {
	return xxx_messageInfo_GetBlockCrossShardByHashRequest.Size(m)
}
func (m *GetBlockCrossShardByHashRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockCrossShardByHashRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockCrossShardByHashRequest proto.InternalMessageInfo

func (m *GetBlockCrossShardByHashRequest) GetFromShard() int32 {
	if m != nil {
		return m.FromShard
	}
	return 0
}

func (m *GetBlockCrossShardByHashRequest) GetToShard() int32 {
	if m != nil {
		return m.ToShard
	}
	return 0
}

func (m *GetBlockCrossShardByHashRequest) GetHashes() [][]byte {
	if m != nil {
		return m.Hashes
	}
	return nil
}

func (m *GetBlockCrossShardByHashRequest) GetCallDepth() int32 {
	if m != nil {
		return m.CallDepth
	}
	return 0
}

type GetBlockCrossShardByHashResponse struct {
	Data                 [][]byte `protobuf:"bytes,1,rep,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockCrossShardByHashResponse) Reset()         { *m = GetBlockCrossShardByHashResponse{} }
func (m *GetBlockCrossShardByHashResponse) String() string { return proto.CompactTextString(m) }
func (*GetBlockCrossShardByHashResponse) ProtoMessage()    {}
func (*GetBlockCrossShardByHashResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a48762df9e8cc53a, []int{17}
}

func (m *GetBlockCrossShardByHashResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockCrossShardByHashResponse.Unmarshal(m, b)
}
func (m *GetBlockCrossShardByHashResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockCrossShardByHashResponse.Marshal(b, m, deterministic)
}
func (m *GetBlockCrossShardByHashResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockCrossShardByHashResponse.Merge(m, src)
}
func (m *GetBlockCrossShardByHashResponse) XXX_Size() int {
	return xxx_messageInfo_GetBlockCrossShardByHashResponse.Size(m)
}
func (m *GetBlockCrossShardByHashResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockCrossShardByHashResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockCrossShardByHashResponse proto.InternalMessageInfo

func (m *GetBlockCrossShardByHashResponse) GetData() [][]byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetChainCommitteeRequest struct {
	Epoch                int32    `protobuf:"varint,1,opt,name=Epoch,proto3" json:"Epoch,omitempty"`
	CommitteeID          int32    `protobuf:"varint,2,opt,name=CommitteeID,proto3" json:"CommitteeID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetChainCommitteeRequest) Reset()         { *m = GetChainCommitteeRequest{} }
func (m *GetChainCommitteeRequest) String() string { return proto.CompactTextString(m) }
func (*GetChainCommitteeRequest) ProtoMessage()    {}
func (*GetChainCommitteeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a48762df9e8cc53a, []int{18}
}

func (m *GetChainCommitteeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetChainCommitteeRequest.Unmarshal(m, b)
}
func (m *GetChainCommitteeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetChainCommitteeRequest.Marshal(b, m, deterministic)
}
func (m *GetChainCommitteeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetChainCommitteeRequest.Merge(m, src)
}
func (m *GetChainCommitteeRequest) XXX_Size() int {
	return xxx_messageInfo_GetChainCommitteeRequest.Size(m)
}
func (m *GetChainCommitteeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetChainCommitteeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetChainCommitteeRequest proto.InternalMessageInfo

func (m *GetChainCommitteeRequest) GetEpoch() int32 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *GetChainCommitteeRequest) GetCommitteeID() int32 {
	if m != nil {
		return m.CommitteeID
	}
	return 0
}

type GetChainCommitteeResponse struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetChainCommitteeResponse) Reset()         { *m = GetChainCommitteeResponse{} }
func (m *GetChainCommitteeResponse) String() string { return proto.CompactTextString(m) }
func (*GetChainCommitteeResponse) ProtoMessage()    {}
func (*GetChainCommitteeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a48762df9e8cc53a, []int{19}
}

func (m *GetChainCommitteeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetChainCommitteeResponse.Unmarshal(m, b)
}
func (m *GetChainCommitteeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetChainCommitteeResponse.Marshal(b, m, deterministic)
}
func (m *GetChainCommitteeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetChainCommitteeResponse.Merge(m, src)
}
func (m *GetChainCommitteeResponse) XXX_Size() int {
	return xxx_messageInfo_GetChainCommitteeResponse.Size(m)
}
func (m *GetChainCommitteeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetChainCommitteeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetChainCommitteeResponse proto.InternalMessageInfo

func (m *GetChainCommitteeResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetHighwayInfosRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHighwayInfosRequest) Reset()         { *m = GetHighwayInfosRequest{} }
func (m *GetHighwayInfosRequest) String() string { return proto.CompactTextString(m) }
func (*GetHighwayInfosRequest) ProtoMessage()    {}
func (*GetHighwayInfosRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a48762df9e8cc53a, []int{20}
}

func (m *GetHighwayInfosRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHighwayInfosRequest.Unmarshal(m, b)
}
func (m *GetHighwayInfosRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHighwayInfosRequest.Marshal(b, m, deterministic)
}
func (m *GetHighwayInfosRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHighwayInfosRequest.Merge(m, src)
}
func (m *GetHighwayInfosRequest) XXX_Size() int {
	return xxx_messageInfo_GetHighwayInfosRequest.Size(m)
}
func (m *GetHighwayInfosRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHighwayInfosRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetHighwayInfosRequest proto.InternalMessageInfo

type HighwayInfo struct {
	PeerInfo             string   `protobuf:"bytes,1,opt,name=PeerInfo,proto3" json:"PeerInfo,omitempty"`
	SupportShards        []int32  `protobuf:"varint,2,rep,packed,name=SupportShards,proto3" json:"SupportShards,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HighwayInfo) Reset()         { *m = HighwayInfo{} }
func (m *HighwayInfo) String() string { return proto.CompactTextString(m) }
func (*HighwayInfo) ProtoMessage()    {}
func (*HighwayInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a48762df9e8cc53a, []int{21}
}

func (m *HighwayInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HighwayInfo.Unmarshal(m, b)
}
func (m *HighwayInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HighwayInfo.Marshal(b, m, deterministic)
}
func (m *HighwayInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HighwayInfo.Merge(m, src)
}
func (m *HighwayInfo) XXX_Size() int {
	return xxx_messageInfo_HighwayInfo.Size(m)
}
func (m *HighwayInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_HighwayInfo.DiscardUnknown(m)
}

var xxx_messageInfo_HighwayInfo proto.InternalMessageInfo

func (m *HighwayInfo) GetPeerInfo() string {
	if m != nil {
		return m.PeerInfo
	}
	return ""
}

func (m *HighwayInfo) GetSupportShards() []int32 {
	if m != nil {
		return m.SupportShards
	}
	return nil
}

type GetHighwayInfosResponse struct {
	Highways             []*HighwayInfo `protobuf:"bytes,1,rep,name=Highways,proto3" json:"Highways,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetHighwayInfosResponse) Reset()         { *m = GetHighwayInfosResponse{} }
func (m *GetHighwayInfosResponse) String() string { return proto.CompactTextString(m) }
func (*GetHighwayInfosResponse) ProtoMessage()    {}
func (*GetHighwayInfosResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a48762df9e8cc53a, []int{22}
}

func (m *GetHighwayInfosResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHighwayInfosResponse.Unmarshal(m, b)
}
func (m *GetHighwayInfosResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHighwayInfosResponse.Marshal(b, m, deterministic)
}
func (m *GetHighwayInfosResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHighwayInfosResponse.Merge(m, src)
}
func (m *GetHighwayInfosResponse) XXX_Size() int {
	return xxx_messageInfo_GetHighwayInfosResponse.Size(m)
}
func (m *GetHighwayInfosResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHighwayInfosResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetHighwayInfosResponse proto.InternalMessageInfo

func (m *GetHighwayInfosResponse) GetHighways() []*HighwayInfo {
	if m != nil {
		return m.Highways
	}
	return nil
}

func init() {
	proto.RegisterEnum("MessageTopicPair_Action", MessageTopicPair_Action_name, MessageTopicPair_Action_value)
	proto.RegisterType((*RegisterRequest)(nil), "RegisterRequest")
	proto.RegisterType((*UserRole)(nil), "UserRole")
	proto.RegisterType((*RegisterResponse)(nil), "RegisterResponse")
	proto.RegisterType((*MessageTopicPair)(nil), "MessageTopicPair")
	proto.RegisterType((*GetBlockShardByHeightRequest)(nil), "GetBlockShardByHeightRequest")
	proto.RegisterType((*GetBlockShardByHeightResponse)(nil), "GetBlockShardByHeightResponse")
	proto.RegisterType((*GetBlockShardByHashRequest)(nil), "GetBlockShardByHashRequest")
	proto.RegisterType((*GetBlockShardByHashResponse)(nil), "GetBlockShardByHashResponse")
	proto.RegisterType((*GetBlockBeaconByHeightRequest)(nil), "GetBlockBeaconByHeightRequest")
	proto.RegisterType((*GetBlockBeaconByHeightResponse)(nil), "GetBlockBeaconByHeightResponse")
	proto.RegisterType((*GetBlockBeaconByHashRequest)(nil), "GetBlockBeaconByHashRequest")
	proto.RegisterType((*GetBlockBeaconByHashResponse)(nil), "GetBlockBeaconByHashResponse")
	proto.RegisterType((*GetBlockCrossShardByHeightRequest)(nil), "GetBlockCrossShardByHeightRequest")
	proto.RegisterType((*GetBlockCrossShardByHeightResponse)(nil), "GetBlockCrossShardByHeightResponse")
	proto.RegisterType((*GetBlockShardToBeaconByHeightRequest)(nil), "GetBlockShardToBeaconByHeightRequest")
	proto.RegisterType((*GetBlockShardToBeaconByHeightResponse)(nil), "GetBlockShardToBeaconByHeightResponse")
	proto.RegisterType((*GetBlockCrossShardByHashRequest)(nil), "GetBlockCrossShardByHashRequest")
	proto.RegisterType((*GetBlockCrossShardByHashResponse)(nil), "GetBlockCrossShardByHashResponse")
	proto.RegisterType((*GetChainCommitteeRequest)(nil), "GetChainCommitteeRequest")
	proto.RegisterType((*GetChainCommitteeResponse)(nil), "GetChainCommitteeResponse")
	proto.RegisterType((*GetHighwayInfosRequest)(nil), "GetHighwayInfosRequest")
	proto.RegisterType((*HighwayInfo)(nil), "HighwayInfo")
	proto.RegisterType((*GetHighwayInfosResponse)(nil), "GetHighwayInfosResponse")
}

func init() { proto.RegisterFile("highway.proto", fileDescriptor_a48762df9e8cc53a) }

var fileDescriptor_a48762df9e8cc53a = []byte{
	// 997 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x57, 0xdd, 0x72, 0xdb, 0x44,
	0x14, 0x96, 0x2c, 0xf9, 0xef, 0x24, 0x4d, 0x9d, 0x43, 0x49, 0x54, 0xd5, 0x49, 0xdd, 0xa5, 0xc9,
	0x78, 0xb8, 0x58, 0xa6, 0x2e, 0xc3, 0x30, 0xc3, 0x55, 0xed, 0xd0, 0x34, 0x50, 0x06, 0x8f, 0x1c,
	0x0f, 0x1d, 0xb8, 0x52, 0xd5, 0x8d, 0xad, 0xc1, 0xf1, 0x1a, 0x49, 0x81, 0xc9, 0x13, 0x70, 0xc9,
	0x1d, 0xaf, 0xc1, 0x25, 0x0f, 0xc1, 0x4b, 0x30, 0xc3, 0x0b, 0xf0, 0x08, 0x8c, 0x56, 0xbf, 0x96,
	0xa5, 0x75, 0x86, 0xbb, 0x5e, 0x59, 0xe7, 0xec, 0xdf, 0xb7, 0xdf, 0xb7, 0xe7, 0xc7, 0x70, 0x6f,
	0xee, 0xce, 0xe6, 0xbf, 0xd8, 0xb7, 0x74, 0xe5, 0xf1, 0x80, 0x93, 0x3f, 0x55, 0xb8, 0x6f, 0xb1,
	0x99, 0xeb, 0x07, 0xcc, 0xb3, 0xd8, 0x4f, 0x37, 0xcc, 0x0f, 0x90, 0x02, 0x8e, 0xf8, 0xf5, 0xb5,
	0x1b, 0x04, 0x8c, 0x8d, 0x6f, 0xde, 0x2e, 0x5c, 0xe7, 0x6b, 0x76, 0x6b, 0xa8, 0x3d, 0xb5, 0xdf,
	0xb6, 0x4a, 0x46, 0xf0, 0x14, 0xf6, 0xbe, 0xb3, 0x97, 0x01, 0x7b, 0xf7, 0x0d, 0xf3, 0x7d, 0x7b,
	0xc6, 0x7c, 0xa3, 0xd6, 0xd3, 0xfa, 0x6d, 0xab, 0xe0, 0xc5, 0x1e, 0xec, 0xa4, 0xab, 0x2f, 0xce,
	0x0c, 0xad, 0xa7, 0xf6, 0x77, 0xad, 0xbc, 0x0b, 0x0f, 0xa0, 0x31, 0x66, 0xcc, 0xbb, 0x38, 0x33,
	0x74, 0x71, 0x5a, 0x6c, 0x21, 0x82, 0x6e, 0xf1, 0x05, 0x33, 0xea, 0xc2, 0x2b, 0xbe, 0xc9, 0x57,
	0xd0, 0x9a, 0xfa, 0xcc, 0x0b, 0xbf, 0xf1, 0x01, 0xd4, 0x5f, 0xdb, 0xb7, 0xcc, 0x8b, 0x41, 0x46,
	0x46, 0xba, 0xaa, 0x96, 0xad, 0x0a, 0x67, 0x4e, 0xe6, 0xb6, 0xf7, 0x4e, 0x9c, 0x5e, 0xb7, 0x22,
	0x83, 0xbc, 0x81, 0x4e, 0x46, 0x82, 0xbf, 0xe2, 0x4b, 0x9f, 0xe1, 0x09, 0xe8, 0x63, 0xdb, 0x0d,
	0xb7, 0xd4, 0xfa, 0x3b, 0x83, 0x7d, 0x1a, 0x5f, 0xe3, 0x92, 0xaf, 0x5c, 0x27, 0x1c, 0xb0, 0xc4,
	0x30, 0x1e, 0xe5, 0x0e, 0xd9, 0x19, 0xb4, 0x69, 0x82, 0x29, 0x46, 0xf9, 0xbb, 0x0a, 0x9d, 0xe2,
	0x4a, 0x34, 0xa0, 0x19, 0xfb, 0x62, 0xc0, 0x89, 0x19, 0xc2, 0x13, 0xd3, 0x62, 0x06, 0x23, 0x03,
	0x3f, 0x06, 0xed, 0x85, 0x13, 0x18, 0x5a, 0x4f, 0xeb, 0xef, 0x0d, 0x8c, 0x0d, 0x24, 0xf4, 0x85,
	0x13, 0xb8, 0x7c, 0x69, 0x85, 0x93, 0xc8, 0x29, 0x34, 0x22, 0x13, 0x01, 0x1a, 0xe3, 0xe9, 0x70,
	0x32, 0x1d, 0x76, 0x14, 0x6c, 0x82, 0x36, 0x9e, 0x0e, 0x3b, 0x6a, 0xf8, 0x11, 0x7a, 0x6a, 0xe4,
	0x6f, 0x15, 0xba, 0xe7, 0x2c, 0x18, 0x2e, 0xb8, 0xf3, 0xa3, 0x20, 0x61, 0x78, 0xfb, 0x8a, 0xb9,
	0xb3, 0x79, 0x90, 0xbc, 0x82, 0x94, 0x29, 0x35, 0xc7, 0x14, 0x9a, 0xd0, 0x9a, 0xac, 0x98, 0xe3,
	0x5e, 0x09, 0x8c, 0x6a, 0xbf, 0x65, 0xa5, 0x36, 0x1e, 0x03, 0xbc, 0xf4, 0xf8, 0x75, 0xb4, 0x8d,
	0x20, 0x58, 0xb7, 0x72, 0x9e, 0x70, 0xed, 0x25, 0x8f, 0x47, 0x75, 0x31, 0x9a, 0xda, 0x21, 0x25,
	0xd1, 0x97, 0x6f, 0xd4, 0x7b, 0x5a, 0x5f, 0xb7, 0x12, 0x33, 0x5c, 0x15, 0xee, 0x31, 0xe6, 0x7c,
	0x61, 0x34, 0xa2, 0x13, 0x13, 0x1b, 0xbb, 0xd0, 0x1e, 0xd9, 0x8b, 0xc5, 0x19, 0x5b, 0x05, 0x73,
	0xa3, 0x29, 0x70, 0x66, 0x0e, 0xf2, 0x1c, 0x8e, 0x2a, 0x6e, 0x18, 0x4b, 0x8c, 0xa0, 0x9f, 0xd9,
	0x81, 0x2d, 0x24, 0xde, 0xb5, 0xc4, 0x37, 0x99, 0x83, 0x59, 0x5c, 0x64, 0xfb, 0x73, 0x39, 0x29,
	0x07, 0xd0, 0x08, 0x27, 0xc5, 0x0f, 0x7f, 0xd7, 0x8a, 0xad, 0x75, 0x78, 0x5a, 0x11, 0xde, 0x33,
	0x78, 0x54, 0x7a, 0x92, 0x04, 0xdc, 0x5f, 0x6a, 0x76, 0xa5, 0x21, 0xb3, 0x1d, 0xbe, 0x2c, 0xaa,
	0x96, 0xd7, 0x47, 0x95, 0xea, 0x53, 0x93, 0xea, 0xa3, 0x55, 0xeb, 0xa3, 0x57, 0xeb, 0x53, 0x97,
	0xe9, 0xd3, 0x28, 0x12, 0xf0, 0x29, 0x1c, 0x57, 0x5d, 0x46, 0xc2, 0xc1, 0x24, 0xa3, 0x2d, 0x5d,
	0x95, 0x53, 0x28, 0xd3, 0x42, 0xad, 0xd6, 0xa2, 0x56, 0x84, 0x32, 0xc8, 0x82, 0x61, 0x7d, 0x53,
	0x09, 0x90, 0x5f, 0x6b, 0xf0, 0x24, 0x59, 0x34, 0xf2, 0xb8, 0xef, 0x97, 0x86, 0x51, 0x17, 0xda,
	0x21, 0x1d, 0xf9, 0x57, 0x93, 0x39, 0x42, 0x5a, 0x2f, 0x79, 0x34, 0x16, 0x61, 0x4a, 0xcc, 0x35,
	0x21, 0x35, 0xa9, 0x90, 0xba, 0x54, 0xc8, 0x7a, 0xb5, 0x90, 0x8d, 0x6a, 0x21, 0x9b, 0x32, 0x21,
	0x5b, 0x45, 0xf6, 0x3e, 0x07, 0x22, 0x23, 0x42, 0xc2, 0xe1, 0xbf, 0x2a, 0x3c, 0x5d, 0x0b, 0x82,
	0x4b, 0x5e, 0xfe, 0xae, 0xe5, 0x34, 0xbe, 0x4f, 0x59, 0xe9, 0x0b, 0x38, 0xd9, 0x72, 0x63, 0x09,
	0x5f, 0xbf, 0xa9, 0xf0, 0xb8, 0x94, 0xea, 0x5c, 0x04, 0xfc, 0xdf, 0x17, 0x97, 0x45, 0x8e, 0x56,
	0x1d, 0x39, 0x7a, 0xf1, 0x3a, 0x9f, 0x41, 0xaf, 0x1a, 0x90, 0xe4, 0x26, 0x16, 0x18, 0xe7, 0x2c,
	0x18, 0xcd, 0x6d, 0x77, 0x99, 0x76, 0x00, 0xb9, 0x2c, 0xfb, 0xe5, 0x8a, 0x3b, 0xf3, 0x24, 0xcb,
	0x0a, 0xa3, 0xd8, 0x3e, 0x44, 0xe8, 0xf3, 0x2e, 0xf2, 0x09, 0x3c, 0x2c, 0xd9, 0x73, 0x03, 0x84,
	0x9a, 0x82, 0x30, 0xe0, 0xe0, 0x9c, 0x05, 0xaf, 0xa2, 0x8e, 0xe8, 0x62, 0x79, 0xc5, 0xfd, 0x18,
	0x02, 0xf9, 0x16, 0x76, 0x72, 0xee, 0x50, 0x6e, 0xd1, 0x8a, 0x2c, 0xaf, 0x78, 0x5c, 0xb2, 0x53,
	0x1b, 0x9f, 0xc2, 0xbd, 0xc9, 0xcd, 0x6a, 0xc5, 0xbd, 0x40, 0xdc, 0x3d, 0x2a, 0x02, 0x75, 0x6b,
	0xdd, 0x49, 0x46, 0x70, 0xb8, 0x71, 0x54, 0x8c, 0xac, 0x0f, 0xad, 0xd8, 0xef, 0xc7, 0xdd, 0xc6,
	0x2e, 0xcd, 0x4d, 0xb4, 0xd2, 0xd1, 0xc1, 0x3f, 0x75, 0xd8, 0x8b, 0x8d, 0x09, 0xf3, 0x7e, 0x76,
	0x1d, 0x86, 0xcf, 0xa0, 0x95, 0xb4, 0x2e, 0xd8, 0xa1, 0x85, 0x56, 0xce, 0xdc, 0xa7, 0xc5, 0xbe,
	0x86, 0x28, 0xf8, 0x06, 0x3e, 0x2c, 0xad, 0x8b, 0x78, 0x44, 0x65, 0x1d, 0x81, 0x79, 0x4c, 0xa5,
	0xe5, 0x94, 0x28, 0x68, 0xc1, 0x07, 0x25, 0x25, 0x0d, 0x1f, 0xd1, 0xea, 0x92, 0x6a, 0x76, 0xa9,
	0xa4, 0x0a, 0x12, 0x05, 0x7f, 0x10, 0x1a, 0x95, 0x54, 0x09, 0xcc, 0xf0, 0x94, 0xe6, 0x0c, 0xf3,
	0x31, 0x95, 0x97, 0x17, 0xa2, 0xe0, 0x14, 0x1e, 0x94, 0xe5, 0x7d, 0xec, 0x52, 0x49, 0x8d, 0x31,
	0x8f, 0xa8, 0xac, 0x58, 0x10, 0x05, 0x67, 0x59, 0x13, 0xb1, 0x99, 0x10, 0x91, 0xd0, 0xad, 0x65,
	0xc3, 0xfc, 0x88, 0x6e, 0xcf, 0xa8, 0x44, 0xc1, 0x55, 0xa1, 0xc5, 0x29, 0x26, 0x13, 0x3c, 0xa1,
	0x77, 0x49, 0xaf, 0xe6, 0x29, 0xbd, 0x53, 0x4e, 0x22, 0x0a, 0xda, 0x22, 0x6e, 0x4b, 0xe3, 0x1d,
	0x7b, 0x74, 0x4b, 0x6e, 0x32, 0x9f, 0xd0, 0x6d, 0xc9, 0x82, 0x28, 0x83, 0x3f, 0x54, 0x38, 0x8c,
	0x5f, 0xf9, 0x88, 0x2f, 0x97, 0xcc, 0x09, 0xb8, 0x97, 0x3c, 0xf7, 0xd7, 0xb0, 0xbf, 0x11, 0xe2,
	0xf8, 0x90, 0x56, 0xa5, 0x12, 0xd3, 0xa4, 0x95, 0x19, 0x81, 0x28, 0xf8, 0x12, 0xee, 0x17, 0x82,
	0x12, 0x0f, 0x69, 0x79, 0x46, 0x30, 0x0d, 0x5a, 0x11, 0xbf, 0x44, 0x19, 0x36, 0xbf, 0xaf, 0x8b,
	0xbf, 0x53, 0x6f, 0x1b, 0xe2, 0xe7, 0xf9, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x97, 0x49, 0xa5,
	0xf4, 0x66, 0x0d, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HighwayServiceClient is the client API for HighwayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HighwayServiceClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	GetBlockShardByHeight(ctx context.Context, in *GetBlockShardByHeightRequest, opts ...grpc.CallOption) (*GetBlockShardByHeightResponse, error)
	GetBlockShardByHash(ctx context.Context, in *GetBlockShardByHashRequest, opts ...grpc.CallOption) (*GetBlockShardByHashResponse, error)
	GetBlockBeaconByHeight(ctx context.Context, in *GetBlockBeaconByHeightRequest, opts ...grpc.CallOption) (*GetBlockBeaconByHeightResponse, error)
	GetBlockBeaconByHash(ctx context.Context, in *GetBlockBeaconByHashRequest, opts ...grpc.CallOption) (*GetBlockBeaconByHashResponse, error)
	GetBlockCrossShardByHeight(ctx context.Context, in *GetBlockCrossShardByHeightRequest, opts ...grpc.CallOption) (*GetBlockCrossShardByHeightResponse, error)
	GetBlockShardToBeaconByHeight(ctx context.Context, in *GetBlockShardToBeaconByHeightRequest, opts ...grpc.CallOption) (*GetBlockShardToBeaconByHeightResponse, error)
	GetBlockCrossShardByHash(ctx context.Context, in *GetBlockCrossShardByHashRequest, opts ...grpc.CallOption) (*GetBlockCrossShardByHashResponse, error)
}

type highwayServiceClient struct {
	cc *grpc.ClientConn
}

func NewHighwayServiceClient(cc *grpc.ClientConn) HighwayServiceClient {
	return &highwayServiceClient{cc}
}

func (c *highwayServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/HighwayService/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *highwayServiceClient) GetBlockShardByHeight(ctx context.Context, in *GetBlockShardByHeightRequest, opts ...grpc.CallOption) (*GetBlockShardByHeightResponse, error) {
	out := new(GetBlockShardByHeightResponse)
	err := c.cc.Invoke(ctx, "/HighwayService/GetBlockShardByHeight", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *highwayServiceClient) GetBlockShardByHash(ctx context.Context, in *GetBlockShardByHashRequest, opts ...grpc.CallOption) (*GetBlockShardByHashResponse, error) {
	out := new(GetBlockShardByHashResponse)
	err := c.cc.Invoke(ctx, "/HighwayService/GetBlockShardByHash", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *highwayServiceClient) GetBlockBeaconByHeight(ctx context.Context, in *GetBlockBeaconByHeightRequest, opts ...grpc.CallOption) (*GetBlockBeaconByHeightResponse, error) {
	out := new(GetBlockBeaconByHeightResponse)
	err := c.cc.Invoke(ctx, "/HighwayService/GetBlockBeaconByHeight", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *highwayServiceClient) GetBlockBeaconByHash(ctx context.Context, in *GetBlockBeaconByHashRequest, opts ...grpc.CallOption) (*GetBlockBeaconByHashResponse, error) {
	out := new(GetBlockBeaconByHashResponse)
	err := c.cc.Invoke(ctx, "/HighwayService/GetBlockBeaconByHash", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *highwayServiceClient) GetBlockCrossShardByHeight(ctx context.Context, in *GetBlockCrossShardByHeightRequest, opts ...grpc.CallOption) (*GetBlockCrossShardByHeightResponse, error) {
	out := new(GetBlockCrossShardByHeightResponse)
	err := c.cc.Invoke(ctx, "/HighwayService/GetBlockCrossShardByHeight", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *highwayServiceClient) GetBlockShardToBeaconByHeight(ctx context.Context, in *GetBlockShardToBeaconByHeightRequest, opts ...grpc.CallOption) (*GetBlockShardToBeaconByHeightResponse, error) {
	out := new(GetBlockShardToBeaconByHeightResponse)
	err := c.cc.Invoke(ctx, "/HighwayService/GetBlockShardToBeaconByHeight", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *highwayServiceClient) GetBlockCrossShardByHash(ctx context.Context, in *GetBlockCrossShardByHashRequest, opts ...grpc.CallOption) (*GetBlockCrossShardByHashResponse, error) {
	out := new(GetBlockCrossShardByHashResponse)
	err := c.cc.Invoke(ctx, "/HighwayService/GetBlockCrossShardByHash", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HighwayServiceServer is the server API for HighwayService service.
type HighwayServiceServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	GetBlockShardByHeight(context.Context, *GetBlockShardByHeightRequest) (*GetBlockShardByHeightResponse, error)
	GetBlockShardByHash(context.Context, *GetBlockShardByHashRequest) (*GetBlockShardByHashResponse, error)
	GetBlockBeaconByHeight(context.Context, *GetBlockBeaconByHeightRequest) (*GetBlockBeaconByHeightResponse, error)
	GetBlockBeaconByHash(context.Context, *GetBlockBeaconByHashRequest) (*GetBlockBeaconByHashResponse, error)
	GetBlockCrossShardByHeight(context.Context, *GetBlockCrossShardByHeightRequest) (*GetBlockCrossShardByHeightResponse, error)
	GetBlockShardToBeaconByHeight(context.Context, *GetBlockShardToBeaconByHeightRequest) (*GetBlockShardToBeaconByHeightResponse, error)
	GetBlockCrossShardByHash(context.Context, *GetBlockCrossShardByHashRequest) (*GetBlockCrossShardByHashResponse, error)
}

// UnimplementedHighwayServiceServer can be embedded to have forward compatible implementations.
type UnimplementedHighwayServiceServer struct {
}

func (*UnimplementedHighwayServiceServer) Register(ctx context.Context, req *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (*UnimplementedHighwayServiceServer) GetBlockShardByHeight(ctx context.Context, req *GetBlockShardByHeightRequest) (*GetBlockShardByHeightResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlockShardByHeight not implemented")
}
func (*UnimplementedHighwayServiceServer) GetBlockShardByHash(ctx context.Context, req *GetBlockShardByHashRequest) (*GetBlockShardByHashResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlockShardByHash not implemented")
}
func (*UnimplementedHighwayServiceServer) GetBlockBeaconByHeight(ctx context.Context, req *GetBlockBeaconByHeightRequest) (*GetBlockBeaconByHeightResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlockBeaconByHeight not implemented")
}
func (*UnimplementedHighwayServiceServer) GetBlockBeaconByHash(ctx context.Context, req *GetBlockBeaconByHashRequest) (*GetBlockBeaconByHashResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlockBeaconByHash not implemented")
}
func (*UnimplementedHighwayServiceServer) GetBlockCrossShardByHeight(ctx context.Context, req *GetBlockCrossShardByHeightRequest) (*GetBlockCrossShardByHeightResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlockCrossShardByHeight not implemented")
}
func (*UnimplementedHighwayServiceServer) GetBlockShardToBeaconByHeight(ctx context.Context, req *GetBlockShardToBeaconByHeightRequest) (*GetBlockShardToBeaconByHeightResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlockShardToBeaconByHeight not implemented")
}
func (*UnimplementedHighwayServiceServer) GetBlockCrossShardByHash(ctx context.Context, req *GetBlockCrossShardByHashRequest) (*GetBlockCrossShardByHashResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlockCrossShardByHash not implemented")
}

func RegisterHighwayServiceServer(s *grpc.Server, srv HighwayServiceServer) {
	s.RegisterService(&_HighwayService_serviceDesc, srv)
}

func _HighwayService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HighwayServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/HighwayService/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HighwayServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HighwayService_GetBlockShardByHeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockShardByHeightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HighwayServiceServer).GetBlockShardByHeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/HighwayService/GetBlockShardByHeight",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HighwayServiceServer).GetBlockShardByHeight(ctx, req.(*GetBlockShardByHeightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HighwayService_GetBlockShardByHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockShardByHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HighwayServiceServer).GetBlockShardByHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/HighwayService/GetBlockShardByHash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HighwayServiceServer).GetBlockShardByHash(ctx, req.(*GetBlockShardByHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HighwayService_GetBlockBeaconByHeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockBeaconByHeightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HighwayServiceServer).GetBlockBeaconByHeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/HighwayService/GetBlockBeaconByHeight",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HighwayServiceServer).GetBlockBeaconByHeight(ctx, req.(*GetBlockBeaconByHeightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HighwayService_GetBlockBeaconByHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockBeaconByHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HighwayServiceServer).GetBlockBeaconByHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/HighwayService/GetBlockBeaconByHash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HighwayServiceServer).GetBlockBeaconByHash(ctx, req.(*GetBlockBeaconByHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HighwayService_GetBlockCrossShardByHeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockCrossShardByHeightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HighwayServiceServer).GetBlockCrossShardByHeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/HighwayService/GetBlockCrossShardByHeight",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HighwayServiceServer).GetBlockCrossShardByHeight(ctx, req.(*GetBlockCrossShardByHeightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HighwayService_GetBlockShardToBeaconByHeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockShardToBeaconByHeightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HighwayServiceServer).GetBlockShardToBeaconByHeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/HighwayService/GetBlockShardToBeaconByHeight",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HighwayServiceServer).GetBlockShardToBeaconByHeight(ctx, req.(*GetBlockShardToBeaconByHeightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HighwayService_GetBlockCrossShardByHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockCrossShardByHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HighwayServiceServer).GetBlockCrossShardByHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/HighwayService/GetBlockCrossShardByHash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HighwayServiceServer).GetBlockCrossShardByHash(ctx, req.(*GetBlockCrossShardByHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HighwayService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "HighwayService",
	HandlerType: (*HighwayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _HighwayService_Register_Handler,
		},
		{
			MethodName: "GetBlockShardByHeight",
			Handler:    _HighwayService_GetBlockShardByHeight_Handler,
		},
		{
			MethodName: "GetBlockShardByHash",
			Handler:    _HighwayService_GetBlockShardByHash_Handler,
		},
		{
			MethodName: "GetBlockBeaconByHeight",
			Handler:    _HighwayService_GetBlockBeaconByHeight_Handler,
		},
		{
			MethodName: "GetBlockBeaconByHash",
			Handler:    _HighwayService_GetBlockBeaconByHash_Handler,
		},
		{
			MethodName: "GetBlockCrossShardByHeight",
			Handler:    _HighwayService_GetBlockCrossShardByHeight_Handler,
		},
		{
			MethodName: "GetBlockShardToBeaconByHeight",
			Handler:    _HighwayService_GetBlockShardToBeaconByHeight_Handler,
		},
		{
			MethodName: "GetBlockCrossShardByHash",
			Handler:    _HighwayService_GetBlockCrossShardByHash_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "highway.proto",
}

// HighwayConnectorServiceClient is the client API for HighwayConnectorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HighwayConnectorServiceClient interface {
	GetChainCommittee(ctx context.Context, in *GetChainCommitteeRequest, opts ...grpc.CallOption) (*GetChainCommitteeResponse, error)
	GetHighwayInfos(ctx context.Context, in *GetHighwayInfosRequest, opts ...grpc.CallOption) (*GetHighwayInfosResponse, error)
}

type highwayConnectorServiceClient struct {
	cc *grpc.ClientConn
}

func NewHighwayConnectorServiceClient(cc *grpc.ClientConn) HighwayConnectorServiceClient {
	return &highwayConnectorServiceClient{cc}
}

func (c *highwayConnectorServiceClient) GetChainCommittee(ctx context.Context, in *GetChainCommitteeRequest, opts ...grpc.CallOption) (*GetChainCommitteeResponse, error) {
	out := new(GetChainCommitteeResponse)
	err := c.cc.Invoke(ctx, "/HighwayConnectorService/GetChainCommittee", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *highwayConnectorServiceClient) GetHighwayInfos(ctx context.Context, in *GetHighwayInfosRequest, opts ...grpc.CallOption) (*GetHighwayInfosResponse, error) {
	out := new(GetHighwayInfosResponse)
	err := c.cc.Invoke(ctx, "/HighwayConnectorService/GetHighwayInfos", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HighwayConnectorServiceServer is the server API for HighwayConnectorService service.
type HighwayConnectorServiceServer interface {
	GetChainCommittee(context.Context, *GetChainCommitteeRequest) (*GetChainCommitteeResponse, error)
	GetHighwayInfos(context.Context, *GetHighwayInfosRequest) (*GetHighwayInfosResponse, error)
}

// UnimplementedHighwayConnectorServiceServer can be embedded to have forward compatible implementations.
type UnimplementedHighwayConnectorServiceServer struct {
}

func (*UnimplementedHighwayConnectorServiceServer) GetChainCommittee(ctx context.Context, req *GetChainCommitteeRequest) (*GetChainCommitteeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChainCommittee not implemented")
}
func (*UnimplementedHighwayConnectorServiceServer) GetHighwayInfos(ctx context.Context, req *GetHighwayInfosRequest) (*GetHighwayInfosResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHighwayInfos not implemented")
}

func RegisterHighwayConnectorServiceServer(s *grpc.Server, srv HighwayConnectorServiceServer) {
	s.RegisterService(&_HighwayConnectorService_serviceDesc, srv)
}

func _HighwayConnectorService_GetChainCommittee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChainCommitteeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HighwayConnectorServiceServer).GetChainCommittee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/HighwayConnectorService/GetChainCommittee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HighwayConnectorServiceServer).GetChainCommittee(ctx, req.(*GetChainCommitteeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HighwayConnectorService_GetHighwayInfos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHighwayInfosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HighwayConnectorServiceServer).GetHighwayInfos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/HighwayConnectorService/GetHighwayInfos",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HighwayConnectorServiceServer).GetHighwayInfos(ctx, req.(*GetHighwayInfosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HighwayConnectorService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "HighwayConnectorService",
	HandlerType: (*HighwayConnectorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetChainCommittee",
			Handler:    _HighwayConnectorService_GetChainCommittee_Handler,
		},
		{
			MethodName: "GetHighwayInfos",
			Handler:    _HighwayConnectorService_GetHighwayInfos_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "highway.proto",
}
