package types

const (
	SHARD_BLOCK_VERSION       = 1
	BFT_VERSION               = 1
	MULTI_VIEW_VERSION        = 2
	SHARD_SFV2_VERSION        = 3
	SHARD_SFV3_VERSION        = 5
	LEMMA2_VERSION            = 6
	BLOCK_PRODUCINGV3_VERSION = 7
	INSTANT_FINALITY_VERSION  = 8
	ADJUST_BLOCKTIME_VERSION  = 9
)
