CreateTransaction(privateKey string, receivers map[string]interface{}, fee float64, privacy float64) (jsonresult.CreateTransactionResult,error)
GetBalanceByPrivateKey(privateKey string) (uint64,error)
GetRewardAmount(paymentAddress string) (map[string]uint64,error)
WithdrawReward(privateKey string, amount float64, privacy float64,info map[string]interface{}) (jsonresult.CreateTransactionResult,error)
CreateAndSendStakingTransaction(privateKey string,receivers map[string]interface{},fee float64, privacy float64, stakeInfo map[string]interface{}) (jsonresult.CreateTransactionResult,error)
CreateAndSendStopAutoStakingTransaction(privateKey string,receivers map[string]interface{},fee float64, privacy float64, stopStakeInfo map[string]interface{}) (jsonresult.CreateTransactionResult,error)
GetCommitteeList(empty string) (jsonresult.CommitteeListsResult,error)
CreateAndSendPrivacyCustomTokenTransaction(privateKey string,receivers map[string]interface{},fee float64, privacy float64, tokenInfo map[string]interface{}) (jsonresult.CreateTransactionResult,error)
CreateAndSendTxWithWithdrawalReqV2(privateKey string, receivers map[string]interface{}, fee float64, privacy float64,reqInfo map[string]interface{}) (jsonresult.CreateTransactionResult,error)         
CreateAndSendTxWithPDEFeeWithdrawalReq(privateKey string, receivers map[string]interface{}, fee float64, privacy float64,reqInfo map[string]interface{}) (jsonresult.CreateTransactionResult,error)    
CreateAndSendTxWithPTokenTradeReq(privateKey string, receivers map[string]interface{}, fee float64, privacy float64,reqInfo map[string]interface{}) (jsonresult.CreateTransactionResult,error)    
CreateAndSendTxWithPTokenCrossPoolTradeReq(privateKey string, receivers map[string]interface{}, fee float64, privacy float64,reqInfo map[string]interface{}) (jsonresult.CreateTransactionResult,error)
CreateAndSendTxWithPRVTradeReq(privateKey string, receivers map[string]interface{}, fee float64, privacy float64,reqInfo map[string]interface{}) (jsonresult.CreateTransactionResult,error)             
CreateAndSendTxWithPRVCrossPoolTradeReq(privateKey string, receivers map[string]interface{}, fee float64, privacy float64,reqInfo map[string]interface{}) (jsonresult.CreateTransactionResult,error)        
CreateAndSendTxWithPTokenContributionV2(privateKey string, receivers map[string]interface{}, fee float64, privacy float64,reqInfo map[string]interface{}) (jsonresult.CreateTransactionResult,error)
CreateAndSendTxWithPRVContributionV2(privateKey string, receivers map[string]interface{}, fee float64, privacy float64,reqInfo map[string]interface{}) (jsonresult.CreateTransactionResult,error)
GetPDEState(data map[string]uint64) (interface{},error)