package config

type ConfigReader interface {
	GetDataDir() string
	GetDatabaseDir() string
	GetMempoolDir() string
	GetLogDir() string
	GetLogLevel() string
	GetLogFileName() string
	GetAddPeers() []string
	GetConnectPeers() []string
	GetListener() string
	GetMaxPeers() int
	GetMaxOurPeers() int
	GetMaxInPeers() int
	GetDiscoverPeers() bool
	GetDiscoverPeersAddress() string
	GetMaxPeersSameShard() int
	GetMaxPeersOtherShard() int
	GetMaxPeersOther() int
	GetMaxPeersNoShard() int
	GetMaxPeersBeacon() int
	GetExternalAddress() string
	GetRPCDisableAuth() bool
	GetRPCUser() string
	GetRPCPass() string
	GetRPCLimitUser() string
	GetRPCLimitPass() string
	GetRPCListeners() []string
	GetRPCWSListeners() []string
	GetRPCKey() string
	GetRPCCert() string
	GetRPCLimitRequestPerDay() int
	GetRPCLimitRequestErrorPerHour() int
	GetRPCMaxClients() int
	GetRPCMaxWsClient() int
	GetRPCQuirks() bool
	GetDisableRPC() bool
	GetDisableTLS() bool
	GetProxy() string
	GetIsLocal() bool
	GetIsTestNet() bool
	GetIsMainNet() bool
	GetTestNetVersion() int
	GetRelayShards() string
	GetEnableWallet() bool
	GetWalletName() string
	GetWalletPassphrase() string
	GetWalletAutoInit() bool
	GetWalletShardID() int
	GetFastStartUp() bool
	GetTxPoolTTL() uint
	GetTxPoolMaxTx() uint64
	GetLimitFee() uint64
	GetIsLoadFromMempool() bool
	GetIsPersistMempool() bool
	GetEnableMining() bool
	GetMiningKeys() string
	GetPrivateKey() string
	GetAccelerator() bool
	GetLibp2pPrivateKey() string
	GetPreloadAddress() string
	GetForceBackup() bool
}

type ParamReader interface {
	GetName() string
	GetNet() uint32
	GetGenesisParam() *genesisParam
	GetCommitteeSize() committeeSize
	GetBlockTime() blockTime
	GetStakingAmountShard() uint64
	GetActiveShards() int
	GetBasicReward() uint64
	GetEpochParam() epochParam
	GetEthContractAddress() string
	GetIncognitoDAOAdress() string
	GetCentralizedWebsitePaymentAddress() string
	GetSwapCommitteeParam() swapCommitteeParam
	GetConsensusParam() consensusParam
	GetBeaconHeightBreakPointBurnAddr() uint64
	GetReplaceStakingTxHeight() uint64
	GetETHRemoveBridgeSigEpoch() uint64
	GetBCHeightBreakPointNewZKP() uint64
	GetEnableFeatureFlags() map[int]uint64
	GetPortalParam() PortalParam
	GetIsBackup() bool
}
